#!/usr/bin/env bash
SERVER=localhost
PORT=10555
</dev/tcp/$SERVER/$PORT
if [ "$?" -ne 0 ]; then
  echo "Connection to $SERVER on port $PORT failed"
  /root/restartpacs
else
  echo "Connection to $SERVER on port $PORT succeeded"
  exit 0
fi

