
package pe.gob.sis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service1Soap", targetNamespace = "http://sis.gob.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service1Soap {


    /**
     * 
     * @param strClave
     * @param strUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSession", action = "http://sis.gob.pe/GetSession")
    @WebResult(name = "GetSessionResult", targetNamespace = "http://sis.gob.pe/")
    @RequestWrapper(localName = "GetSession", targetNamespace = "http://sis.gob.pe/", className = "pe.gob.sis.GetSession")
    @ResponseWrapper(localName = "GetSessionResponse", targetNamespace = "http://sis.gob.pe/", className = "pe.gob.sis.GetSessionResponse")
    public String getSession(
        @WebParam(name = "strUsuario", targetNamespace = "http://sis.gob.pe/")
        String strUsuario,
        @WebParam(name = "strClave", targetNamespace = "http://sis.gob.pe/")
        String strClave);

    /**
     * 
     * @param strCorrelativo
     * @param strNroContrato
     * @param strNroDocumento
     * @param strDisa
     * @param strDni
     * @param strTipoFormato
     * @param strTipoDocumento
     * @param strAutorizacion
     * @param intOpcion
     * @return
     *     returns pe.gob.sis.ResultQueryAsegurado
     */
    @WebMethod(operationName = "ConsultarAfiliadoSIS", action = "http://sis.gob.pe/ConsultarAfiliadoSIS")
    @WebResult(name = "ConsultarAfiliadoSISResult", targetNamespace = "http://sis.gob.pe/")
    @RequestWrapper(localName = "ConsultarAfiliadoSIS", targetNamespace = "http://sis.gob.pe/", className = "pe.gob.sis.ConsultarAfiliadoSIS")
    @ResponseWrapper(localName = "ConsultarAfiliadoSISResponse", targetNamespace = "http://sis.gob.pe/", className = "pe.gob.sis.ConsultarAfiliadoSISResponse")
    public ResultQueryAsegurado consultarAfiliadoSIS(
        @WebParam(name = "intOpcion", targetNamespace = "http://sis.gob.pe/")
        int intOpcion,
        @WebParam(name = "strAutorizacion", targetNamespace = "http://sis.gob.pe/")
        String strAutorizacion,
        @WebParam(name = "strDni", targetNamespace = "http://sis.gob.pe/")
        String strDni,
        @WebParam(name = "strTipoDocumento", targetNamespace = "http://sis.gob.pe/")
        String strTipoDocumento,
        @WebParam(name = "strNroDocumento", targetNamespace = "http://sis.gob.pe/")
        String strNroDocumento,
        @WebParam(name = "strDisa", targetNamespace = "http://sis.gob.pe/")
        String strDisa,
        @WebParam(name = "strTipoFormato", targetNamespace = "http://sis.gob.pe/")
        String strTipoFormato,
        @WebParam(name = "strNroContrato", targetNamespace = "http://sis.gob.pe/")
        String strNroContrato,
        @WebParam(name = "strCorrelativo", targetNamespace = "http://sis.gob.pe/")
        String strCorrelativo);

    /**
     * 
     * @param strCorrelativo
     * @param strNroContrato
     * @param strNroDocumento
     * @param strDisa
     * @param strDni
     * @param strTipoFormato
     * @param strTipoDocumento
     * @param strAutorizacion
     * @param intOpcion
     * @return
     *     returns pe.gob.sis.ResultQueryJuntos
     */
    @WebMethod(operationName = "ConsultarAfiliadoJuntos", action = "http://sis.gob.pe/ConsultarAfiliadoJuntos")
    @WebResult(name = "ConsultarAfiliadoJuntosResult", targetNamespace = "http://sis.gob.pe/")
    @RequestWrapper(localName = "ConsultarAfiliadoJuntos", targetNamespace = "http://sis.gob.pe/", className = "pe.gob.sis.ConsultarAfiliadoJuntos")
    @ResponseWrapper(localName = "ConsultarAfiliadoJuntosResponse", targetNamespace = "http://sis.gob.pe/", className = "pe.gob.sis.ConsultarAfiliadoJuntosResponse")
    public ResultQueryJuntos consultarAfiliadoJuntos(
        @WebParam(name = "intOpcion", targetNamespace = "http://sis.gob.pe/")
        int intOpcion,
        @WebParam(name = "strAutorizacion", targetNamespace = "http://sis.gob.pe/")
        String strAutorizacion,
        @WebParam(name = "strDni", targetNamespace = "http://sis.gob.pe/")
        String strDni,
        @WebParam(name = "strTipoDocumento", targetNamespace = "http://sis.gob.pe/")
        String strTipoDocumento,
        @WebParam(name = "strNroDocumento", targetNamespace = "http://sis.gob.pe/")
        String strNroDocumento,
        @WebParam(name = "strDisa", targetNamespace = "http://sis.gob.pe/")
        String strDisa,
        @WebParam(name = "strTipoFormato", targetNamespace = "http://sis.gob.pe/")
        String strTipoFormato,
        @WebParam(name = "strNroContrato", targetNamespace = "http://sis.gob.pe/")
        String strNroContrato,
        @WebParam(name = "strCorrelativo", targetNamespace = "http://sis.gob.pe/")
        String strCorrelativo);

    /**
     * 
     * @param strCorrelativo
     * @param strNroContrato
     * @param strNroDocumento
     * @param strDisa
     * @param strDni
     * @param strTipoFormato
     * @param strTipoDocumento
     * @param strAutorizacion
     * @param intOpcion
     * @return
     *     returns pe.gob.sis.ResultQueryAsegurado
     */
    @WebMethod(operationName = "ConsultarAfiliadoFuaE", action = "http://sis.gob.pe/ConsultarAfiliadoFuaE")
    @WebResult(name = "ConsultarAfiliadoFuaEResult", targetNamespace = "http://sis.gob.pe/")
    @RequestWrapper(localName = "ConsultarAfiliadoFuaE", targetNamespace = "http://sis.gob.pe/", className = "pe.gob.sis.ConsultarAfiliadoFuaE")
    @ResponseWrapper(localName = "ConsultarAfiliadoFuaEResponse", targetNamespace = "http://sis.gob.pe/", className = "pe.gob.sis.ConsultarAfiliadoFuaEResponse")
    public ResultQueryAsegurado consultarAfiliadoFuaE(
        @WebParam(name = "intOpcion", targetNamespace = "http://sis.gob.pe/")
        int intOpcion,
        @WebParam(name = "strAutorizacion", targetNamespace = "http://sis.gob.pe/")
        String strAutorizacion,
        @WebParam(name = "strDni", targetNamespace = "http://sis.gob.pe/")
        String strDni,
        @WebParam(name = "strTipoDocumento", targetNamespace = "http://sis.gob.pe/")
        String strTipoDocumento,
        @WebParam(name = "strNroDocumento", targetNamespace = "http://sis.gob.pe/")
        String strNroDocumento,
        @WebParam(name = "strDisa", targetNamespace = "http://sis.gob.pe/")
        String strDisa,
        @WebParam(name = "strTipoFormato", targetNamespace = "http://sis.gob.pe/")
        String strTipoFormato,
        @WebParam(name = "strNroContrato", targetNamespace = "http://sis.gob.pe/")
        String strNroContrato,
        @WebParam(name = "strCorrelativo", targetNamespace = "http://sis.gob.pe/")
        String strCorrelativo);

    /**
     * 
     * @param strCorrelativo
     * @param strNroContrato
     * @param strNroDocumento
     * @param strDisa
     * @param strDni
     * @param strTipoFormato
     * @param strTipoDocumento
     * @param strAutorizacion
     * @param intOpcion
     * @return
     *     returns pe.gob.sis.ResultQueryAseguradoFISSAL
     */
    @WebMethod(operationName = "ConsultarAfiliadoFissal", action = "http://sis.gob.pe/ConsultarAfiliadoFissal")
    @WebResult(name = "ConsultarAfiliadoFissalResult", targetNamespace = "http://sis.gob.pe/")
    @RequestWrapper(localName = "ConsultarAfiliadoFissal", targetNamespace = "http://sis.gob.pe/", className = "pe.gob.sis.ConsultarAfiliadoFissal")
    @ResponseWrapper(localName = "ConsultarAfiliadoFissalResponse", targetNamespace = "http://sis.gob.pe/", className = "pe.gob.sis.ConsultarAfiliadoFissalResponse")
    public ResultQueryAseguradoFISSAL consultarAfiliadoFissal(
        @WebParam(name = "intOpcion", targetNamespace = "http://sis.gob.pe/")
        int intOpcion,
        @WebParam(name = "strAutorizacion", targetNamespace = "http://sis.gob.pe/")
        String strAutorizacion,
        @WebParam(name = "strDni", targetNamespace = "http://sis.gob.pe/")
        String strDni,
        @WebParam(name = "strTipoDocumento", targetNamespace = "http://sis.gob.pe/")
        String strTipoDocumento,
        @WebParam(name = "strNroDocumento", targetNamespace = "http://sis.gob.pe/")
        String strNroDocumento,
        @WebParam(name = "strDisa", targetNamespace = "http://sis.gob.pe/")
        String strDisa,
        @WebParam(name = "strTipoFormato", targetNamespace = "http://sis.gob.pe/")
        String strTipoFormato,
        @WebParam(name = "strNroContrato", targetNamespace = "http://sis.gob.pe/")
        String strNroContrato,
        @WebParam(name = "strCorrelativo", targetNamespace = "http://sis.gob.pe/")
        String strCorrelativo);

}
