<%@include file="/includes/validateUser.jsp"%>
<%@page errorPage="/includes/error.jsp"%>
<%

%>
<bean:define id="transaction" name="be.mxs.webapp.wl.session.SessionContainerFactory.WO_SESSION_CONTAINER" property="currentTransactionVO"/>
<table class="list" width="100%" cellspacing="1">
    <tr>
        <td class="admin" width="<%=sTDAdminWidth%>"><%=getTran(request,"openclinic.chuk","tracnet.admission.form.complaints",sWebLanguage)%></td>
        <td class="admin2">
            <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANTECEDENT_FLUCONAZOL_COMMENT")%> class="text" cols="100" rows="5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANTECEDENT_FLUCONAZOL_COMMENT" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANTECEDENT_FLUCONAZOL_COMMENT" property="value"/></textarea>
        </td>
    </tr>
</table>
<br>
<table class="list" width="100%" cellspacing="0" cellpadding="0">
    <tr class="admin">
        <td colspan="2"><%=getTran(request,"openclinic.chuk","tracnet.admission.form.screening",sWebLanguage)%></td>
    </tr>
    <tr>
        <td width="50%" height="100%">
            <table width="100%" cellspacing="1" cellpadding="0" height="100%">
                <tr>
                    <td class="admin" width="<%=sTDAdminWidth%>" rowspan="6"><%=getTran(request,"openclinic.chuk","tracnet.admission.form.cough",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH;value=medwan.common.yes" property="value" outputString="checked"/> id="cbcoughyes"><%=getLabel(request,"web.occup","medwan.common.yes",sWebLanguage,"cbcoughyes")%>
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH" property="itemId"/>]>.value" value="medwan.common.no" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH;value=medwan.common.no" property="value" outputString="checked"/> id="cbcoughno"><%=getLabel(request,"web.occup","medwan.common.no",sWebLanguage,"cbcoughno")%>
                     </td>
                </tr>
                <tr>
                    <td class="admin2">
                        <input type="checkbox" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_PRODUCTIVE")%> name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_PRODUCTIVE" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_PRODUCTIVE;value=medwan.common.yes" property="value" outputString="checked"/> id="cbcoughproductive"><%=getLabel(request,"openclinic.chuk","tracnet.admission.form.cough.productive",sWebLanguage,"cbcoughproductive")%>
                        <br>(<%=getTran(request,"openclinic.chuk","tracnet.admission.form.cough.productive.aspect",sWebLanguage)%>
                        <input type="text" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_PRODUCTIVE_ASPECT")%> class="text" size="50" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_PRODUCTIVE_ASPECT" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_PRODUCTIVE_ASPECT" property="value"/>"/>)
                     </td>
                </tr>
                <tr>
                    <td class="admin2">
                        <input type="checkbox" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DRY")%> name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DRY" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DRY;value=medwan.common.yes" property="value" outputString="checked"/> id="cbcoughdry"><%=getLabel(request,"openclinic.chuk","tracnet.admission.form.cough.dry",sWebLanguage,"cbcoughdry")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin2">
                        <input type="checkbox" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_HEMOPTYSIE")%> name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_HEMOPTYSIE" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_HEMOPTYSIE;value=medwan.common.yes" property="value" outputString="checked"/> id="cbcoughhemo"><%=getLabel(request,"openclinic.chuk","tracnet.admission.form.cough.hemo",sWebLanguage,"cbcoughhemo")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin2">
                        <input type="checkbox" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DYSPNEE")%> name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DYSPNEE" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DYSPNEE;value=medwan.common.yes" property="value" outputString="checked"/> id="cbcoughdyspnee"><%=getLabel(request,"openclinic.chuk","tracnet.admission.form.cough.dyspnee",sWebLanguage,"cbcoughdyspnee")%>
                        <br><%=getTran(request,"openclinic.chuk","tracnet.admission.form.cough.productive.dyspnee.duration",sWebLanguage)%>:
                        <input type="text" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DYSPNEE_DAYS")%> class="text" size="5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DYSPNEE_DAYS" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DYSPNEE_DAYS" property="value"/>"/>
                        <%=getTran(request,"openclinic.chuk","tracnet.admission.form.cough.productive.dyspnee.duration.days",sWebLanguage)%>
                        <input type="text" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DYSPNEE_WEEKS")%> class="text" size="5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DYSPNEE_WEEKS" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DYSPNEE_WEEKS" property="value"/>"/>
                        <%=getTran(request,"openclinic.chuk","tracnet.admission.form.cough.productive.dyspnee.duration.weeks",sWebLanguage)%>
                        <input type="text" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DYSPNEE_MONTHS")%> class="text" size="5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DYSPNEE_MONTHS" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_DYSPNEE_MONTHS" property="value"/>"/>
                        <%=getTran(request,"openclinic.chuk","tracnet.admission.form.cough.productive.dyspnee.duration.months",sWebLanguage)%>
                    </td>
                </tr>
                <tr>
                    <td class="admin2">
                        <input type="checkbox" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_THORAX")%> name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_THORAX" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_THORAX;value=medwan.common.yes" property="value" outputString="checked"/> id="cbcoughthorax"><%=getLabel(request,"openclinic.chuk","tracnet.admission.form.cough.thorax",sWebLanguage,"cbcoughthorax")%>
                        <br>
                        <%=getTran(request,"openclinic.chuk","tracnet.admission.form.cough.comments",sWebLanguage)%>
                        <input type="text" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_COMMENT")%> class="text" size="50" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_COMMENT" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_COUGH_COMMENT" property="value"/>"/>
                    </td>
                </tr>
                <tr>
                    <td class="admin" ><%=getTran(request,"openclinic.chuk","tracnet.admission.form.sweat",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_SWEAT")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_SWEAT" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_SWEAT;value=medwan.common.yes" property="value" outputString="checked"/> id="cbsweatyes"><%=getLabel(request,"web.occup","medwan.common.yes",sWebLanguage,"cbsweatyes")%>
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_SWEAT")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_SWEAT" property="itemId"/>]>.value" value="medwan.common.no" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_SWEAT;value=medwan.common.no" property="value" outputString="checked"/> id="cbsweatno"><%=getLabel(request,"web.occup","medwan.common.no",sWebLanguage,"cbsweatno")%>
                        <br>
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_SWEAT_LESS_3_WEEKS")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_SWEAT_LESS_3_WEEKS" property="itemId"/>]>.value" value="lower.3.weeks" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_SWEAT_LESS_3_WEEKS;value=lower.3.weeks" property="value" outputString="checked"/> id="cbsweat3yes"><%=getLabel(request,"web.occup","lower.3.weeks",sWebLanguage,"cbsweat3yes")%>
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_SWEAT_LESS_3_WEEKS")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_SWEAT_LESS_3_WEEKS" property="itemId"/>]>.value" value="higher.3.weeks" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_SWEAT_LESS_3_WEEKS;value=higher.3.weeks" property="value" outputString="checked"/> id="cbsweat3no"><%=getLabel(request,"web.occup","higher.3.weeks",sWebLanguage,"cbsweat3no")%>
                    </td>
                </tr>
            </table>
        </td>
        <td>
            <table width="100%" cellspacing="1" cellpadding="0">
                <tr>
                    <td class="admin" ><%=getTran(request,"openclinic.chuk","tracnet.admission.form.fever",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER;value=medwan.common.yes" property="value" outputString="checked"/> id="cbfeveryes"><%=getLabel(request,"web.occup","medwan.common.yes",sWebLanguage,"cbfeveryes")%>
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER" property="itemId"/>]>.value" value="medwan.common.no" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER;value=medwan.common.no" property="value" outputString="checked"/> id="cbfeverno"><%=getLabel(request,"web.occup","medwan.common.no",sWebLanguage,"cbfeverno")%>
                        <br><%=getTran(request,"openclinic.chuk","tracnet.admission.form.cough.productive.dyspnee.duration",sWebLanguage)%>:
                        <input type="text" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER_DAYS")%> class="text" size="5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER_DAYS" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER_DAYS" property="value"/>"/>
                        <%=getTran(request,"openclinic.chuk","tracnet.admission.form.cough.productive.dyspnee.duration.days",sWebLanguage)%>
                        <input type="text" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER_WEEKS")%> class="text" size="5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER_WEEKS" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER_WEEKS" property="value"/>"/>
                        <%=getTran(request,"openclinic.chuk","tracnet.admission.form.cough.productive.dyspnee.duration.weeks",sWebLanguage)%>
                        <input type="text" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER_MONTHS")%> class="text" size="5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER_MONTHS" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_FEVER_MONTHS" property="value"/>"/>
                        <%=getTran(request,"openclinic.chuk","tracnet.admission.form.cough.productive.dyspnee.duration.months",sWebLanguage)%>
                    </td>
                </tr>
                <tr>
                    <td class="admin" ><%=getTran(request,"openclinic.chuk","tracnet.admission.form.tbc.contact",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TBC_CONTACT")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TBC_CONTACT" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TBC_CONTACT;value=medwan.common.yes" property="value" outputString="checked"/> id="cbtbcyes"><%=getLabel(request,"web.occup","medwan.common.yes",sWebLanguage,"cbtbcyes")%>
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TBC_CONTACT")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TBC_CONTACT" property="itemId"/>]>.value" value="medwan.common.no" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TBC_CONTACT;value=medwan.common.no" property="value" outputString="checked"/> id="cbtbcno"><%=getLabel(request,"web.occup","medwan.common.no",sWebLanguage,"cbtbcno")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin" ><%=getTran(request,"openclinic.chuk","tracnet.admission.form.loss.weight",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_LOSS_WEIGHT")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_LOSS_WEIGHT" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_LOSS_WEIGHT;value=medwan.common.yes" property="value" outputString="checked"/> id="cbweightyes"><%=getLabel(request,"web.occup","medwan.common.yes",sWebLanguage,"cbweightyes")%>
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_LOSS_WEIGHT")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_LOSS_WEIGHT" property="itemId"/>]>.value" value="medwan.common.no" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_LOSS_WEIGHT;value=medwan.common.no" property="value" outputString="checked"/> id="cbweightno"><%=getLabel(request,"web.occup","medwan.common.no",sWebLanguage,"cbweightno")%>
                    </td>
                </tr>
                 <tr>
                    <td class="admin" ><%=getTran(request,"openclinic.chuk","tracnet.admission.form.diarrhoea",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA;value=medwan.common.yes" property="value" outputString="checked"/> id="cbdiayes"><%=getLabel(request,"web.occup","medwan.common.yes",sWebLanguage,"cbdiayes")%>
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA" property="itemId"/>]>.value" value="medwan.common.no" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA;value=medwan.common.no" property="value" outputString="checked"/> id="cbdiano"><%=getLabel(request,"web.occup","medwan.common.no",sWebLanguage,"cbdiano")%>
                        <br>
                        <%=getTran(request,"openclinic.chuk","tracnet.admission.form.diarrhoea.motion",sWebLanguage)%>
                        <input type="text" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_MOTION")%> class="text" size="5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_MOTION" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_MOTION" property="value"/>"/>
                        <br>
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_LESS_1_MONTH")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_LESS_1_MONTH" property="itemId"/>]>.value" value="lower.1.month" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_LESS_1_MONTH;value=lower.1.month" property="value" outputString="checked"/> id="cbdia1yes"><%=getLabel(request,"web.occup","lower.1.month",sWebLanguage,"cbdia1yes")%>
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_LESS_1_MONTH")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_LESS_1_MONTH" property="itemId"/>]>.value" value="higher.1.month" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_LESS_1_MONTH;value=higher.1.month" property="value" outputString="checked"/> id="cbdia1no"><%=getLabel(request,"web.occup","higher.1.month",sWebLanguage,"cbdia1no")%>
                        <br>
                        <%=getTran(request,"openclinic.chuk","tracnet.admission.form.diarrhoea.blood",sWebLanguage)%>
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_BLOOD")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_BLOOD" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_BLOOD;value=medwan.common.yes" property="value" outputString="checked"/> id="cbdiabloodyes"><%=getLabel(request,"web.occup","medwan.common.yes",sWebLanguage,"cbdiabloodyes")%>
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_BLOOD")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_BLOOD" property="itemId"/>]>.value" value="medwan.common.no" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_BLOOD;value=medwan.common.no" property="value" outputString="checked"/> id="cbdiabloodno"><%=getLabel(request,"web.occup","medwan.common.no",sWebLanguage,"cbdiabloodno")%>
                        <br>
                        <%=getTran(request,"openclinic.chuk","tracnet.admission.form.cough.comments",sWebLanguage)%>
                        <input type="text" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_COMMENT")%> class="text" size="50" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_COMMENT" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DIARRHOEA_COMMENT" property="value"/>"/>
                    </td>
                </tr>
                <tr>
                    <td class="admin" ><%=getTran(request,"openclinic.chuk","tracnet.admission.form.ist",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_IST")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_IST" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_IST;value=medwan.common.yes" property="value" outputString="checked"/> id="cbistyes"><%=getLabel(request,"web.occup","medwan.common.yes",sWebLanguage,"cbistyes")%>
                        <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_IST")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_IST" property="itemId"/>]>.value" value="medwan.common.no" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_IST;value=medwan.common.no" property="value" outputString="checked"/> id="cbistno"><%=getLabel(request,"web.occup","medwan.common.no",sWebLanguage,"cbistno")%>
                        <br>
                        <%=getTran(request,"openclinic.chuk","tracnet.admission.form.ist.complaints",sWebLanguage)%>
                        <input type="text" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_IST_COMPLAINTS")%> class="text" size="50" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_IST_COMPLAINTS" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_IST_COMPLAINTS" property="value"/>"/>
                    </td>
                </tr>
                <tr>
                    <td class="admin" ><%=getTran(request,"openclinic.chuk","tracnet.admission.form.date.last.bleeding",sWebLanguage)%></td>
                    <td class="admin2">
                        <input type="text" class="text" size="12" maxLength="10" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DATE_LAST_BLEEDING" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_DATE_LAST_BLEEDING" property="value"/>" id="last_bleeding_date" OnBlur='checkDate(this)'>
                        <script>writeMyDate("last_bleeding_date");</script>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<br>
<table class="list" width="100%" cellspacing="1">
    <tr>
        <td class="admin" width="<%=sTDAdminWidth%>"><%=getTran(request,"openclinic.chuk","tracnet.admission.form.performance",sWebLanguage)%></td>
        <td class="admin2">
            <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_PERFORMANCE")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_PERFORMANCE" property="itemId"/>]>.value" value="lower.acivity" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_PERFORMANCE;value=normal.activity" property="value" outputString="checked"/> id="cbperformance_normal"><%=getLabel(request,"web.occup","normal.activity",sWebLanguage,"cbperformance_normal")%>
            <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_PERFORMANCE")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_PERFORMANCE" property="itemId"/>]>.value" value="in.bed.lower.50" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_PERFORMANCE;value=in.bed.lower.50" property="value" outputString="checked"/> id="cbperformance_lower"><%=getLabel(request,"web.occup","in.bed.lower.50",sWebLanguage,"cbperformance_lower")%>
            <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_PERFORMANCE")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_PERFORMANCE" property="itemId"/>]>.value" value="in.bed.higher.50" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_PERFORMANCE;value=in.bed.higher.50" property="value" outputString="checked"/> id="cbperformance_higher"><%=getLabel(request,"web.occup","in.bed.higher.50",sWebLanguage,"cbperformance_higher")%>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran(request,"openclinic.chuk","tracnet.admission.form.antecedents.hiv",sWebLanguage)%></td>
        <td class="admin2">
            <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ANTECEDENT_HIV")%> class="text" cols="100" rows="2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ANTECEDENT_HIV" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ANTECEDENT_HIV" property="value"/></textarea>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran(request,"openclinic.chuk","tracnet.admission.form.antecedents.not.hiv",sWebLanguage)%></td>
        <td class="admin2">
            <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ANTECEDENT_NOT_HIV")%> class="text" cols="100" rows="2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ANTECEDENT_NOT_HIV" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ANTECEDENT_NOT_HIV" property="value"/></textarea>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran(request,"openclinic.chuk","tracnet.admission.form.antecedents.surgical",sWebLanguage)%></td>
        <td class="admin2">
            <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ANTECEDENT_SURGICAL")%> class="text" cols="100" rows="2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ANTECEDENT_SURGICAL" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ANTECEDENT_SURGICAL" property="value"/></textarea>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran(request,"openclinic.chuk","tracnet.admission.form.antecedents.gyneco",sWebLanguage)%></td>
        <td class="admin2">
            <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ANTECEDENT_GYNECO")%> class="text" cols="100" rows="2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ANTECEDENT_GYNECO" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ANTECEDENT_GYNECO" property="value"/></textarea>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran(request,"openclinic.chuk","tracnet.admission.form.antecedents.tobacco",sWebLanguage)%></td>
        <td class="admin2">
            <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TOBACCO")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TOBACCO" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TOBACCO;value=medwan.common.yes" property="value" outputString="checked"/> id="cbtobaccoyes"><%=getLabel(request,"web.occup","medwan.common.yes",sWebLanguage,"cbtobaccoyes")%>
            <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TOBACCO")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TOBACCO" property="itemId"/>]>.value" value="medwan.common.no" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TOBACCO;value=medwan.common.no" property="value" outputString="checked"/> id="cbtobaccono"><%=getLabel(request,"web.occup","medwan.common.no",sWebLanguage,"cbtobaccono")%>
            <br>
            <%=getTran(request,"openclinic.chuk","tracnet.admission.form.antecedents.tobacco.a.day",sWebLanguage)%>
            <input type="text" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TOBACCO_A_DAY")%> class="text" size="5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TOBACCO_A_DAY" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_TOBACCO_A_DAY" property="value"/>" onblur="isNumber(this)"/>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran(request,"openclinic.chuk","tracnet.admission.form.antecedents.alcohol",sWebLanguage)%></td>
        <td class="admin2">
            <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ALCOHOL")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ALCOHOL" property="itemId"/>]>.value" value="medwan.common.yes" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ALCOHOL;value=medwan.common.yes" property="value" outputString="checked"/> id="cbalcoholyes"><%=getLabel(request,"web.occup","medwan.common.yes",sWebLanguage,"cbalcoholyes")%>
            <input <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ALCOHOL")%> type="radio" onDblClick="uncheckRadio(this);" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ALCOHOL" property="itemId"/>]>.value" value="medwan.common.no" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ALCOHOL;value=medwan.common.no" property="value" outputString="checked"/> id="cbalcoholno"><%=getLabel(request,"web.occup","medwan.common.no",sWebLanguage,"cbalcoholno")%>
            <br>
            <%=getTran(request,"openclinic.chuk","tracnet.admission.form.antecedents.alcohol.a.day",sWebLanguage)%>
            <input type="text" <%=setRightClick(session,"ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ALCOHOL_A_WEEK")%> class="text" size="5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ALCOHOL_A_WEEK" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ADMISSION_FORM_ANAMNESE_ALCOHOL_A_WEEK" property="value"/>" onblur="isNumber(this)"/>
        </td>
    </tr>
</table>